
on:
  release:
    types:
      - created
jobs:
  build:
    name: Build Executable
    runs-on: windows-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Fetch go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}
      - name: Fetch goversioninfo
        run: go install -v github.com/josephspurrier/goversioninfo/cmd/goversioninfo
      - name: Build the executable
        shell: bash
        run: ./build.sh -useVersion=${{ github.event.release.tag_name }}
      - name: copy executable to release subdirectory
        run: copy ./mp3repair.exe release
      - name: create the zip file
        uses: thedoctor0/zip-release@0.7.6
        with:
          filename: mp3repair.zip
          path: release
      - name: Upload the zip file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./mp3repair.zip
          file_glob: true